/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gant' at '17-6-13 上午11:30' with Gradle 3.0
 *
 * @author gant, @date 17-6-13 上午11:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
